# -*- coding: utf-8 -*-
from django.utils.translation import ugettext as _

CANADIAN_CITIES = [
    ["", _("Choisir une ville")],
    ["agadir", _("Agadir")],
    ["ain_el_aouda", _("Aïn El Aouda")],
    ["ain_harrouda", _("Aïn Harrouda")],
    ["ait_melloul", _("Aït Melloul")],
    ["al_hoceima", _("Al Hoceïma")],
    ["assilah", _("Assilah")],
    ["azemmour", _("Azemmour")],
    ["azilal", _("Azilal")],
    ["azrou", _("Azrou")],
    ["bejaad", _("Bejaad")],
    ["ben_ahmed", _("Ben Ahmed")],
    ["ben_guerir", _("Ben Guerir")],
    ["ben_slimane", _("Ben Slimane")],
    ["ben_taieb", _("Ben Taïeb")],
    ["beni_mellal", _("Beni Mellal")],
    ["berkane", _("Berkane")],
    ["berrechid", _("Berrechid")],
    ["bouarfa", _("Bouarfa")],
    ["bouizakarne", _("Bouizakarne")],
    ["boujdour", _("Boujdour")],
    ["boulemane", _("Boulemane")],
    ["bouskoura", _("Bouskoura")],
    ["bouznika", _("Bouznika")],
    ["casablanca", _("Casablanca")],
    ["chefchaouen", _("Chefchaouen")],
    ["chichaoua", _("Chichaoua")],
    ["dakhla", _("Dakhla")],
    ["demnate", _("Demnate")],
    ["deroua", _("Deroua")],
    ["echemmaia", _("Echemmaia")],
    ["el_hajeb", _("El Hajeb")],
    ["el_jadida", _("El Jadida")],
    ["el_mansouria", _("El Mansouria")],
    ["errachidia", _("Errachidia")],
    ["errich", _("Er-Rich")],
    ["essaouira", _("Essaouira")],
    ["essemara", _("Es-Semara")],
    ["fes", _("Fès")],
    ["figuig", _("Figuig")],
    ["fnideq", _("Fnideq")],
    ["fquih_ben_salah", _("Fquih Ben Salah")],
    ["goulmima", _("Goulmima")],
    ["guelmim", _("Guelmim")],
    ["guercif", _("Guercif")],
    ["guisser", _("Guisser")],
    ["ifrane", _("Ifrane")],
    ["imintanoute", _("Imintanoute")],
    ["inezgane", _("Inezgane")],
    ["jamaat_shaim", _("Jamaat Shaim")],
    ["jerada", _("Jerada")],
    ["jorf", _("Jorf")],
    ["kalaat_mgouna", _("Kalaat M'Gouna")],
    ["kasba_tadla", _("Kasba Tadla")],
    ["kenitra", _("Kénitra")],
    ["khemisset", _("Khémisset")],
    ["khenifra", _("Khénifra")],
    ["khouribga", _("Khouribga")],
    ["ksar_el_kebir", _("Ksar El Kébir")],
    ["laaounate", _("Laâounate")],
    ["laayoune", _("Laayoune")],
    ["lbir_jdid", _("Lbir Jdid")],
    ["loualidia", _("Loualidia")],
    ["madagh", _("Madagh")],
    ["marrakech", _("Marrakech")],
    ["martil", _("Martil")],
    ["massa", _("Massa")],
    ["mdiq", _("M'Diq")],
    ["mehdya", _("Mehdya")],
    ["meknes", _("Meknès")],
    ["midelt", _("Midelt")],
    ["missour", _("Missour")],
    ["mohammédia", _("Mohammédia")],
    ["moulay_abdallah", _("Moulay Abdallah")],
    ["moulay_ali_cherif", _("Moulay Ali Chérif")],
    ["moulay_bouazza", _("Moulay Bouazza")],
    ["moulay_bousselham", _("Moulay Bousselham")],
    ["moulay_brahim", _("Moulay Brahim")],
    ["mrirt", _("M'Rirt")],
    ["nador", _("Nador")],
    ["nouaceur", _("Nouaceur")],
    ["ouaouizeght", _("Ouaouizeght")],
    ["oued_zem", _("Oued Zem")],
    ["ouezzane", _("Ouezzane")],
    ["ouislane", _("Ouislane")],
    ["oujda", _("Oujda")],
    ["oulmes", _("Oulmès")],
    ["rabat", _("Rabat")],
    ["safi", _("Safi")],
    ["saidia", _("Saïdia")],
    ["sale", _("Salé")],
    ["sefrou", _("Sefrou")],
    ["settat", _("Settat")],
    ["sidi_bennour", _("Sidi Bennour")],
    ["sidi_bouknadel", _("Sidi Bouknadel")],
    ["sidi_bouzid", _("Sidi Bouzid")],
    ["sidi_kacem", _("Sidi Kacem")],
    ["sidi_rahhal", _("Sidi Rahhal")],
    ["sidi_slimane", _("Sidi Slimane")],
    ["sidi_smail", _("Sidi Smaïl")],
    ["skhirate", _("Skhirate")],
    ["soualem", _("Soualem")],
    ["tafraout", _("Tafraout")],
    ["tanger", _("Tanger")],
    ["tan_tan", _("Tan-Tan")],
    ["taounate", _("Taounate")],
    ["tarfaya", _("Tarfaya")],
    ["taourirt", _("Taourirt")],
    ["taroudant", _("Taroudant")],
    ["tata", _("Tata")],
    ["taza", _("Taza")],
    ["temara", _("Témara")],
    ["tetouan", _("Tétouan")],
    ["tinghir", _("Tinghir")],
    ["tit_mellil", _("Tit Mellil")],
    ["tiznit", _("Tiznit")],
    ["youssoufia", _("Youssoufia")],
    ["zag", _("Zag")],
    ["zagora", _("Zagora")],
    ["zemamra", _("Zemamra")],
]

PROPERTIES_TYPES = [
    ["", _("Type de la propriété")],
    ["apartment", _("Appartement")],
    ["duplex", _("Duplex")],
    ["quadruplex", _("Quadruplex")],
    ["quintuplex", _("Quintuplex")],
    ["multiple_housing", _("Multi logements")],
    ["ground_floor_house", _("Maison de plain-pied")],
    ["two_or_more_storey", _("Maison à étages")],
    ["split_level", _("Maison à paliers multiples")],
    ["one_and_a_half_storey_house", _("Maison à un étage et demi")],
    ["mobile_home", _("Maison mobile")],
    ["house", _("Maison")],
    ["loft_studio", _("Loft / Studio")],
    ["commercial", _("Commerciale")],
    ["industrial", _("Industrielle")],
    ["company", _("Entreprise (fonds de commerce)")],
    ["bulk", _("Bulk (block sale)")],
    ["land", _("Terre")],
    ["lot", _("Terrain")],
    ["farm", _("Ferme")],
    ["hobby_farm", _("Fermette")],
    ["other", _("Autre")],
]

BUILDINGS_TYPES = [
    ["", _("Choisir un type")],
    ["detached", _("Isolé")],
    ["semi_detached", _("Jumelé")],
    ["attached", _("En rangée")],
    ["attached_corner_unit", _("En rangée sur coin")],
    ["quadrex", _("Quadrex")],
    ["5plex", _("5 plex et plus")],
]

BEDROOMS_NUMBER = [
    ["", _("Selectionner un nombre")],
    ["1", _("1")],
    ["2", _("2")],
    ["3", _("3")],
    ["4", _("4")],
    ["5_", _("5 et plus")],
]

BATHROOMS_NUMBER = [
    ["", _("Selectionner un nombre")],
    ["1", _("1")],
    ["2", _("2")],
    ["3_", _("3 et plus")],
]

CONSTRUCTION_AGE = [
    ["", _("Choisir l'âge du construction")],
    ["newly_built", _("Récemment construit")],
    ["10_years_and_less", _("Moins de 10 ans")],
    ["more_than_10_years", _("10 ans et plus")],
]

ITEMS_STATUS = [
    ["for_sale", _("À vendre")],
    ["for_rent", _("À louer")],
    ["sold", _("Vendue")],
]

PRICES_RANGES = [
    ["", _("Non spécifié")],
    ["0_250", _("Moins de 250 000 DH")],
    ["250_350", _("250 000 DH - 350 000 DH")],
    ["350_450", _("350 000 DH - 450 000 DH")],
    ["450_550", _("450 000 DH - 550 000 DH")],
    ["550_1000", _("Plus de 550 000 DH")],
]

PRICES_RANGES_VALUES = {
    "0_250": {
        "min": 0,
        "max": 249999,
    },
    "250_350": {
        "min": 250000,
        "max": 349999,
    },
    "350_450": {
        "min": 350000,
        "max": 449999,
    },
    "450_550": {
        "min": 450000,
        "max": 549999,
    },
    "550_1000": {
        "min": 550000,
        "max": 10000000,
    }
}

TYPES = (
    ("", _("Autre")),
    ("achteur", _("Achteur")),
    ("vendeur", _("Vendeur")),
    ("locataire", _("Locataire"))
)

